name: example
description: A web app that uses AngularDart Components
version: 1.0.0
# homepage: https://www.example.com
author: insinfo <insinfo2008@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha+19
  http: ^0.12.0+2
  stream_transform: ^0.0.19
  sass_builder: ^2.1.3
  js: ^0.6.1+1
  money: ^0.2.1
  decimal: ^0.3.4
  c3: ^0.1.0
  dio: ^3.0.3

  essential_components: 
    path: ../

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.7.2
  build_test: ^0.10.9+1
  build_web_compilers: ^2.7.1
  pedantic: ^1.8.0
  test: ^1.6.0
