name: essential_components
description: A library for AngularDart developers. This library will implement several key components for the fast development of web applications with AngularDart.
version: 0.1.89

homepage: https://github.com/insinfo/essential_components
authors: 
  - Isaque Neves <insinfo2008@gmail.com> 
  - Thiago Cunha <thiagosantoscunha@outlook.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: '>=5.3.0 <6.2.0'
  angular_components: '>=0.13.0 <0.15.0'
  angular_forms: '>=2.1.2 <2.5.0'
  angular_router: '>=2.0.0-alpha <2.5.0'
  intl: ^0.15.8
  #ng_fontawesome: ^5.7.2+2  
  decimal: ^0.3.5
  xml: ^3.7.0
  #spreadsheet_decoder: ^1.0.1
  archive: ^2.0.13
  uuid: ^2.0.4
  http: ^0.12.0+4
  http_parser: ^3.1.3
  sass_builder: ^2.1.2
  dart_browser_loader: ^0.0.6+1
  js: ^0.6.1+1

dev_dependencies:  
  build_runner: any
  build_test: any
  build_web_compilers: any
  pedantic: ^1.7.0
  test: ^1.6.0
