name: essential_components
description: A library for AngularDart developers. This library will implement several key components for the fast development of web applications with AngularDart.
version: 1.9.21

homepage: https://github.com/insinfo/essential_components
authors: 
  - Isaque Neves <insinfo2008@gmail.com> 
  - Thiago Cunha <thiagosantoscunha@outlook.com>

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  angular: '>=5.3.0 <6.2.0'
  angular_forms: '>=2.1.2 <4.0.0'
  angular_router: '>=2.0.0-alpha <4.0.0'
  intl: '>=0.15.8 <2.5.0'
  decimal: '>=0.3.5 <2.5.0' #used in DecimalValueAccessor 
  xml: '>=3.7.0 <4.0.0' #use in feedparser\parser.dart:
  #uuid: ^2.0.4
  http: '>=0.12.0 <2.0.0' #use in essential_recaptcha.dart:
  #http_parser: ^3.1.3
  dart_browser_loader: ^0.0.6+1
  js: ^0.6.1+1
  essential_xlsx: '>=1.0.0 <2.5.0'
  essential_rest: '>=1.0.18 <2.5.0'
  sass_builder: '>=2.1.2 <2.5.0'

dev_dependencies:  
  build_runner: any
  build_test: any
  build_web_compilers: any
  pedantic: ^1.7.0
  test: ^1.6.0
  
