name: essential_components
description: A starting point for Dart libraries or applications.
version: 0.1.14
homepage: https://github.com/insinfo/essential_components
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  intl: ^0.15.8
  #ng_fontawesome: ^5.7.2+2
  sass_builder: ^2.1.3
  decimal: ^0.3.4
  xml: ^3.5.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
