name: essential_components
description: A starting point for Dart libraries or applications.
version: 0.0.4
# homepage: https://www.example.com
author: insinfo <insinfo2008@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  ng_fontawesome: ^5.7.2+2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
