name: essential_components
description: A starting point for Dart libraries or applications.
version: 0.0.5
homepage: https://github.com/insinfo/essential_components
author: insinfo <insinfo2008@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_forms: ^2.0.0
  intl: ^0.15.8
  ng_fontawesome: ^5.7.2+2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
